# This overlay composes the complete deployment of dwco. It uses the "support" overlay and adds the actual operator deployment,
# the configuration configmap and patches the deployment with templatized values from the manager_image_patch.yaml

namespace: devworkspace-che

namePrefix: devworkspace-che-

commonLabels:
  app.kubernetes.io/name: devworkspace-che-operator
  app.kubernetes.io/part-of: devworkspace-che-operator
  
generatorOptions:
  disableNameSuffixHash: true

resources:
- ../../components/crd
- ../../components/rbac
- ../../components/manager

configMapGenerator:
- name: configmap
  envs:
  - config.properties

patchesStrategicMerge:
- manager_image_patch.yaml
