# This patch sets the image used for deployment according to environment variables.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: devworkspace-che-operator
        image: quay.io/che-incubator/devworkspace-che-operator:latest
        imagePullPolicy: Always
